### ISSUE TITLE
Angular 9 - Ivy - but could not be resolved  to an NgModule class

### ISSUE THREAD

**Issue by wendelstam** [lokenxo/ng2-fittext#28]
I have problems compiling with Ivy enabled. I get the following message. Any ideas anbody?

> ERROR in node_modules/ng2-fittext/ng2-fittext.module.d.ts:1:22 - error NG6002: Appears in the NgModule.imports of DashboardModule, but could not be resolved 
> to an NgModule class
>     
>     1 export declare class Ng2FittextModule {
>                            ~~~~~~~~~~~~~~~~
>     src/app/app.module.ts:80:12 - error NG1010: Value at position 11 in the NgModule.imports of AppModule is not a reference: [object Object]

**Comment by SjurWarEagle** [comment]
If you compile ng2-fittext with 

    "angularCompilerOptions": {
        "strictMetadataEmit": true,
        "enableIvy": false, <----
        "skipTemplateCodegen": true
    },

in yout tsconfig.json and updated packages it's working for me.

Not sure if this is the best way, but it's working flawlessly.

**Comment by thisloke** [comment]
> If you compile ng2-fittext with
> 
> ```
> "angularCompilerOptions": {
>     "strictMetadataEmit": true,
>     "enableIvy": false, <----
>     "skipTemplateCodegen": true
> },
> ```
> 
> in yout tsconfig.json and updated packages it's working for me.
> 
> Not sure if this is the best way, but it's working flawlessly.

In this way you will not use ivy, it will be good as a temporary workaround.

I will investigate soon the issue. 
Thanks for the report!

**Comment by wendelstam** [comment]
Thanks for the response but we're currently porting our app to ivy so disabling it is not an option unfortunately.
Have not been able to figure out the root cause yet, but if I do I can create a PR. Any idea what causes it?

**Comment by SjurWarEagle** [comment]
Just to avoid misunderstandings, I proposed to compile just ng2-fittext  with disabled ivy, not your application.

**Comment by wendelstam** [comment]
Sorry, I read it to fast apparently. Thanks for the clarification @SjurWarEagle

**Comment by datawaslost** [comment]
There are a few variations of this same issue floating around the angular discussions that may be of help in determining what the issue is:

https://github.com/angular/angular/issues/35255
https://github.com/angular/angular/issues/34755

**Comment by JoostK** [comment]
The package.json of `ng2-fittext` refers to non-existent files for its `main`, `module` and `es2015` properties. There's actually no reference at all to the `index.js` file that _does_ exist. This is likely the root cause of why ngcc is unable the process the package.

For @lokenxo, I would recommend to look into fixing those paths in the generated NPM package. If you stick to publishing just the ES5 format, you'd need to ensure that "module" refers to "./index.js". The other properties (`main` and `es2015`) should be removed as you don't publish UMD nor ESM2015 formats. Alternatively, consider using the ng-packagr tool or the CLI's library support, which uses ng-packagr behind the scenes. That tool would package the library according to Angular Package Format so that you don't have to think about getting all the details right.

---

Package consumers can workaround the issue by teaching ngcc where to find the index file. For that, create a file called `ngcc.config.js` next to the root `package.json` file:

```js
module.exports = {
  packages: {
    "ng2-fittext": {
      entryPoints: {
        ".": {
          "override": {
            "main": undefined,
            "module": "./index.js",
            "es2015": undefined,
          },
        },
      },
    },
  },
};
```

This configuration would be temporary as long as no new version is published.

**Comment by JoostK** [comment]
`ng2-fittext` appears to be shipping a `package.json` file that refers to non-existent files, hence ngcc can't process it. [I provided more info and a potential workaround here](https://github.com/lokenxo/ng2-fittext/issues/28#issuecomment-585080352).

**Comment by thisloke** [comment]
I just release a fix in the latest version (1.2.9).
The problem was related, as @JoostK mentioned in his post, in an uncorrect configuration of package.json.

I solve it using ng-packagr to create the bundle, more easier and no workaround needed.

@wendelstam try to update the version of ng2-fittext with the 1.2.9 as mentioned before.

**Comment by JoostK** [comment]
@lokenxo It doesn't seem that 1.2.9 has been published correctly. The workspace root folder has been published, where only the `dist` directory should have been published.

**Comment by thisloke** [comment]
@JoostK it's the default behaviour of publish with ng-packagr, i will fix later publishing only the dist folder. _(Edit: my bad, is not because ng-packger but because i didn't update the npm publish script in package.json, now i'm fixing)_

In every case, in the repository at `example/dev` folder you will find a blank angular 9 project with ivy enabled using ng2-fittext. 
It make the build correctly.

**Comment by wendelstam** [comment]
Thanks guys - I tried it now and it works!

Appreciate the quick fix.

**Comment by benhickson** [comment]
@lokenxo I'm hitting this same issue in an Angular 9 project, with version `1.2.12`

**Comment by ljupcospeci** [comment]
@lokenxo Same here.
