### ISSUE TITLE
Can't bind to 'fittext' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by zinoroman** [lokenxo/ng2-fittext#3]
Hello!
I am using angular 4.1.0 along with ionic-angular 3.2.1 and I encountered next problem
```
Unhandled Promise rejection: Template parse errors:
Can't bind to 'fittext' since it isn't a known property of 'div'. 
```

I imported `Ng2FittextModule` and declared `Ng2FittextModule` in my module

```
import { Ng2FittextModule } from 'ng2-fittext/ng2fittext';

@NgModule({
    imports: [
        ...
        Ng2FittextModule,
        ....
    ],
})
export class AppModule { }
```

My HTML:
```
<div class="round-progress-wrapper"
        #roundProgressWrapper>
         <div [fittext]="true"
                 [activateOnResize]="true"
                 [container]="roundProgressWrapper">50</div>
</div>
```

What I have done wrong and how can i fix it?

**Comment by thisloke** [comment]
Hi
> Unhandled Promise rejection: Template parse errors:
Can't bind to 'fittext' since it isn't a known property of 'div'. 

it says that you doesn't import correctly the directive in your module.

In which component do you have this template?

```
<div class="round-progress-wrapper"
        #roundProgressWrapper>
         <div [fittext]="true"
                 [activateOnResize]="true"
                 [container]="roundProgressWrapper">50</div>
</div>
```

Check if you have declared the component which contains the template where you use the fittext in your AppModule.

Example: http://plnkr.co/edit/v0TQaYepV4E2Heur02j5?p=preview

**Comment by zinoroman** [comment]
Yes! I am sorry, this is my fault, I was just inattentive)
Thank you so much for your quick answer and your work!
