### ISSUE TITLE
Text sizing only applies on resize

### ISSUE THREAD

**Issue by madmacc** [lokenxo/ng2-fittext#41]
It doesn't apply unless I resize my browser window.  Not sure why.  

"ng2-fittext": "^1.2.12"

```
 <div *ngIf="appUser" class="user">
    <div class="anchor" #container  [routerLink]="['/user']">
      <div [fittext]="true" [activateOnResize]="false" [container]="container" [maxFontSize]="13">{{appUser.firstName}}</div>
    </div>
  </div>
```

**Comment by FlavioSantoro92** [comment]
Same problem here, same situation. I tried everything but only when the screen is redrawn the resize will work.

**Comment by yurik94** [comment]
Same for me...

**Comment by madmacc** [comment]
I just had to remove it in the end I couldn't figure it out.

**Comment by yurik94** [comment]
> I just had to remove it in the end I couldn't figure it out.

I got it working (the npmjs published version seems 8 months old rather than the master here)
I have simply copied the directive part to my project and the i used this sample code in a ionic 3 project (Angular 5):

```
<div class="inner" #upper_inner>
   <div class="text" [fittext]="true" [activateOnResize]="true" [container]="upper_inner" [modelToWatch]="upper_text">{{upper_text}}
    </div>
</div>
```

I had to change the directive's constructor like this:

`constructor(public el: ElementRef, public renderer: Renderer2) {`

**Comment by rbalet** [comment]
> > I just had to remove it in the end I couldn't figure it out.
> 
> I got it working (the npmjs published version seems 8 months old rather than the master here)
> I have simply copied the directive part to my project and the i used this sample code in a ionic 3 project (Angular 5):
> 
> ```
> <div class="inner" #upper_inner>
>    <div class="text" [fittext]="true" [activateOnResize]="true" [container]="upper_inner" [modelToWatch]="upper_text">{{upper_text}}
>     </div>
> </div>
> ```
> 
> I had to change the directive's constructor like this:
> 
> `constructor(public el: ElementRef, public renderer: Renderer2) {`

This did not work for me by the way. As of today, the problem still exists on ionic v > 3.

**Comment by hararia** [comment]
You can trigger a window resize event with something like:

` window.dispatchEvent(new Event('resize'));
`

**Comment by shaya-tabit** [comment]
I found 2 ways that worked for me - 
1. Provide a dynamic variable to `[modelToWatch]`
2. Dispatch a resize event within a `ngAfterViewInit -> setTimeout` (less preferred)

**Comment by thisloke** [comment]
By design, just using **activateOnResize=true** should solve every problem, the font resizing will triggered when window size it's changed. Anyway, if you want to force-trigger the computation un can change the model passed as parameter to **modelToWatch** or as a workaround **window.dispatchEvent(new Event('resize'))** looks working fine.

**Comment by thisloke** [comment]
See latest comment
